name: SonarQube Integration

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Integration
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=test
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarqube.chartably-development.com
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
